// Command citymapgen turns DFProfiler's bossmap stylesheet into citymap.txt.
//
// The city's shape - which coordinates are blocks and which are the gaps you have
// to walk around - is not in anything the game publishes. The player record knows
// where you are, the public stats feed knows about buildings and streets on a grid
// that does not line up with city coordinates at all, and the bossmap feed only
// says what has spawned. DFProfiler's map knows, because it draws the city: its
// stylesheet lists every real block by coordinate and paints it.
//
// So this is run by hand, once, and its output is committed. It is not part of the
// build and df-hud never fetches the stylesheet at runtime: the city changes when
// the game changes, which is to say almost never, and a program that re-derived its
// map from someone else's CSS on every start would be both fragile and rude.
//
//	curl -o bosstable.css https://www.dfprofiler.com/css/bosstable.css
//	go run ./tools/citymapgen bosstable.css > citymap.txt
//
// See knowledge/city-map.md for what was checked against the result.
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// The stylesheet is one long line of minified rules, each of which may name
// hundreds of coordinates. Rules are taken in order and later ones win, the way a
// browser resolves them: several coordinates are painted twice.
var (
	ruleRe   = regexp.MustCompile(`([^{}]+)\{([^}]*)\}`)
	coordRe  = regexp.MustCompile(`\.coord\.x(\d+)\.y(\d+)`)
	colourRe = regexp.MustCompile(`background-color:\s*([^;]+)`)
	borderRe = regexp.MustCompile(`border-(left|right|top|bottom)-color:\s*#fff`)
	rgbaRe   = regexp.MustCompile(`rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([0-9.]+))?\)`)
	hslaRe   = regexp.MustCompile(`hsla?\((\d+),\s*(\d+)%,\s*(\d+)%(?:,\s*([0-9.]+))?\)`)
)

type point struct{ X, Y int }

type colour struct {
	R, G, B uint8
	A       float64
}

func (c colour) String() string {
	return fmt.Sprintf("%02x%02x%02x %.2f", c.R, c.G, c.B, c.A)
}

// luminance orders the shades so the map reads as a gradient rather than as
// whatever order the stylesheet happens to list them in. Rec. 601, which is close
// enough for sorting sixteen colours.
func (c colour) luminance() float64 {
	return 0.299*float64(c.R) + 0.587*float64(c.G) + 0.114*float64(c.B)
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("citymapgen: ")

	in := os.Stdin
	if len(os.Args) > 1 {
		f, err := os.Open(os.Args[1])
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		in = f
	}
	css, err := io.ReadAll(in)
	if err != nil {
		log.Fatal(err)
	}

	blocks := map[point]colour{}
	// A divider is a white cell border, and they come in pairs: the right edge of
	// one column and the left edge of the next. Only one side of each pair is
	// recorded, as "the boundary runs before this column".
	dividerX := map[int]bool{}
	dividerY := map[int]bool{}

	for _, rule := range ruleRe.FindAllStringSubmatch(string(css), -1) {
		sel, decl := rule[1], rule[2]
		coords := coordRe.FindAllStringSubmatch(sel, -1)
		if len(coords) == 0 {
			continue
		}
		var pts []point
		for _, c := range coords {
			x, _ := strconv.Atoi(c[1])
			y, _ := strconv.Atoi(c[2])
			pts = append(pts, point{x, y})
		}
		if m := colourRe.FindStringSubmatch(decl); m != nil {
			col, ok := parseColour(strings.TrimSpace(m[1]))
			if !ok {
				log.Fatalf("cannot parse colour %q", m[1])
			}
			for _, p := range pts {
				blocks[p] = col
			}
		}
		for _, b := range borderRe.FindAllStringSubmatch(decl, -1) {
			for _, p := range pts {
				switch b[1] {
				case "left":
					dividerX[p.X] = true
				case "top":
					dividerY[p.Y] = true
				}
			}
		}
	}
	if len(blocks) == 0 {
		log.Fatal("no coordinates found - is this the right stylesheet?")
	}

	minX, minY, maxX, maxY := bounds(blocks)
	shades := assignLetters(blocks)

	out := os.Stdout
	fmt.Fprintf(out, `# The city: which coordinates are blocks, and how the map is shaded.
#
# GENERATED by tools/citymapgen from DFProfiler's bossmap stylesheet, which is the
# only published thing that knows the city's shape. Do not edit by hand.
# knowledge/city-map.md records where it comes from and what was checked.
#
# %d blocks in a %dx%d rectangle. Everything else is a gap: not a place, and not
# somewhere you can walk through on the way to somewhere else.

origin %d %d
size %d %d
`, len(blocks), maxX-minX+1, maxY-minY+1, minX, minY, maxX-minX+1, maxY-minY+1)

	fmt.Fprintf(out, "\n# A district boundary runs before this column or row. Nine districts on the\n"+
		"# main map plus the southern strip, which is what df_tradezone counts.\n")
	for _, x := range sortedKeys(dividerX) {
		fmt.Fprintf(out, "divider x %d\n", x)
	}
	for _, y := range sortedKeys(dividerY) {
		fmt.Fprintf(out, "divider y %d\n", y)
	}

	fmt.Fprintf(out, "\n# Shades, ordered dark to light. rrggbb then the alpha they are drawn with.\n")
	for _, s := range shades {
		fmt.Fprintf(out, "shade %c %s\n", s.letter, s.colour)
	}

	fmt.Fprintf(out, "\n# x increases to the right from %d, y downwards from %d. '.' is a gap.\nmap\n", minX, minY)
	letterOf := map[colour]byte{}
	for _, s := range shades {
		letterOf[s.colour] = s.letter
	}
	for y := minY; y <= maxY; y++ {
		row := make([]byte, 0, maxX-minX+1)
		for x := minX; x <= maxX; x++ {
			if col, ok := blocks[point{x, y}]; ok {
				row = append(row, letterOf[col])
			} else {
				row = append(row, '.')
			}
		}
		fmt.Fprintf(out, "%s\n", row)
	}
}

type shade struct {
	letter byte
	colour colour
}

// assignLetters gives every distinct colour a stable letter. Sorted by luminance so
// that the committed map is diffable: adding a block must not renumber the rest.
func assignLetters(blocks map[point]colour) []shade {
	seen := map[colour]bool{}
	var cols []colour
	for _, c := range blocks {
		if !seen[c] {
			seen[c] = true
			cols = append(cols, c)
		}
	}
	sort.Slice(cols, func(i, j int) bool {
		if cols[i].luminance() != cols[j].luminance() {
			return cols[i].luminance() < cols[j].luminance()
		}
		return cols[i].String() < cols[j].String()
	})
	const letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	if len(cols) > len(letters) {
		log.Fatalf("%d shades is more than there are letters", len(cols))
	}
	out := make([]shade, 0, len(cols))
	for i, c := range cols {
		out = append(out, shade{letters[i], c})
	}
	return out
}

func bounds(blocks map[point]colour) (minX, minY, maxX, maxY int) {
	first := true
	for p := range blocks {
		if first {
			minX, minY, maxX, maxY = p.X, p.Y, p.X, p.Y
			first = false
			continue
		}
		minX = min(minX, p.X)
		minY = min(minY, p.Y)
		maxX = max(maxX, p.X)
		maxY = max(maxY, p.Y)
	}
	return
}

func sortedKeys(m map[int]bool) []int {
	out := make([]int, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Ints(out)
	return out
}

func parseColour(s string) (colour, bool) {
	if m := rgbaRe.FindStringSubmatch(s); m != nil {
		r, _ := strconv.Atoi(m[1])
		g, _ := strconv.Atoi(m[2])
		b, _ := strconv.Atoi(m[3])
		return colour{uint8(r), uint8(g), uint8(b), alpha(m[4])}, true
	}
	if m := hslaRe.FindStringSubmatch(s); m != nil {
		h, _ := strconv.Atoi(m[1])
		sat, _ := strconv.Atoi(m[2])
		l, _ := strconv.Atoi(m[3])
		r, g, b := hslToRGB(float64(h), float64(sat)/100, float64(l)/100)
		return colour{r, g, b, alpha(m[4])}, true
	}
	// The stylesheet uses exactly one named colour, for the outposts.
	if s == "green" {
		return colour{0, 128, 0, 1}, true
	}
	return colour{}, false
}

func alpha(s string) float64 {
	if s == "" {
		return 1
	}
	a, err := strconv.ParseFloat(s, 64)
	if err != nil {
		return 1
	}
	return a
}

func hslToRGB(h, s, l float64) (uint8, uint8, uint8) {
	c := (1 - abs(2*l-1)) * s
	hp := h / 60
	x := c * (1 - abs(mod(hp, 2)-1))
	var r, g, b float64
	switch int(hp) % 6 {
	case 0:
		r, g, b = c, x, 0
	case 1:
		r, g, b = x, c, 0
	case 2:
		r, g, b = 0, c, x
	case 3:
		r, g, b = 0, x, c
	case 4:
		r, g, b = x, 0, c
	default:
		r, g, b = c, 0, x
	}
	m := l - c/2
	return round((r + m) * 255), round((g + m) * 255), round((b + m) * 255)
}

func abs(f float64) float64 {
	if f < 0 {
		return -f
	}
	return f
}

func mod(a, b float64) float64 {
	for a >= b {
		a -= b
	}
	return a
}

func round(f float64) uint8 {
	if f < 0 {
		return 0
	}
	if f > 255 {
		return 255
	}
	return uint8(f + 0.5)
}
